language: ruby
sudo: false

cache:
  bundler: true

services:
  - memcached

bundler_args: --without test --jobs 3 --retry 3
before_install:
  - gem install bundler -v=1.11.2

before_script:
  - bundle update

script: 'ci/travis.rb'

env:
  matrix:
    - "GEM=railties"
    - "GEM=ap,am,amo,ares,as"
    - "GEM=ar:mysql"
    - "GEM=ar:mysql2"
    - "GEM=ar:sqlite3"
    - "GEM=ar:postgresql"

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.8
  - 2.2.6
  - 2.3.2

notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#rails-contrib"
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "YA1alef1ESHWGFNVwvmVGCkMe4cUy4j+UcNvMUESraceiAfVyRMAovlQBGs6\n9kBRm7DHYBUXYC2ABQoJbQRLDr/1B5JPf/M8+Qd7BKu8tcDC03U01SMHFLpO\naOs/HLXcDxtnnpL07tGVsm0zhMc5N8tq4/L3SHxK7Vi+TacwQzI="
